### ISSUE TITLE
Add linting to CI

### ISSUE THREAD

**Issue by wlach** [graph-paper-org/graph-paper#28]
Per https://github.com/graph-paper-org/graph-paper/pull/27#discussion_r405142342 we have a linting command but it is currently failing. We should add it to CI. The settings seem good to me (eslint base recommendations + airbnb + prettier)

**Comment by hamilton** [comment]
@wlach as of #33, the linting command _should_ pass.

**Comment by openjck** [comment]
CI is currently running `npx eslint .` which doesn't check Svelte files. We should update it to run `npm run lint` once #33 is resolved.
