### ISSUE TITLE
port over OptionMenu.svelte from Incline

### ISSUE THREAD

**Issue by hamilton** [graph-paper-org/graph-paper#5]

**Comment by openjck** [comment]
As part of this work, we should fix the issue where multiple OptionMenu components can be opened simultaneously. Instead, we want opening one to close the others. We should include a story that demonstrates this by showing several OptionMenu components side-by-side.

**Comment by openjck** [comment]
Hamilton also mentioned that:

> I am hoping we can move away from having a giant click DIV underneath the thing. I think this is a gross antipattern I’d like to avoid in graph-paper. Much better to just temporarily listen for another click event.

**Comment by openjck** [comment]
Updated to fix the `<div>`/side-by-side issue. There's a story demonstrating that it works.
