### ISSUE TITLE
Approval Poll Model Example breaks storybook

### ISSUE THREAD

**Issue by knowtheory** [graph-paper-org/graph-paper#57]
Hey!

If you're clicking around in the storybook as soon as you hit the [Approval Poll Model Example](https://graph-paper-org.github.io/graph-paper/?path=/story/line--approval-poll-model-example) the storybook no longer dynamically loads graph contents in any of the examples.

Looks like it's failing to serve/load the resource/data for the poll which then breaks the app.

**Comment by hamilton** [comment]
Oh no! Thanks for reporting. I'm having trouble reproducing this issue locally. Did you happen to run `npx lerna bootstrap` before `npm run storybook`?

**Comment by hamilton** [comment]
It looks like this same issue is true for the currently-deployed storybook as well.

**Comment by hamilton** [comment]
Believe this should now be fixed. Thanks for reporting @knowtheory ~
