### ISSUE TITLE
Line stories somewhat broken

### ISSUE THREAD

**Issue by wlach** [graph-paper-org/graph-paper#88]
It looks like the change 87c404dfcd1423fa9f8ab1194560d3695aa1d5e8 may have broken the line stories (and maybe other stories). See e.g. this one which now gives a console error when I try to hover over the graphs:

![Screen Shot 2020-05-07 at 4 25 12 PM](https://user-images.githubusercontent.com/20569/81341321-56d0eb00-907f-11ea-8140-5cbc11d02000.png)

/cc @hamilton

**Comment by hamilton** [comment]
thanks for reporting, will look into it.
